Project setup
alkemyTech/OT292-server pull request #1
Opened 2022-09-15 20:29 UTC by NovoaMartin

Typescript and Eslint setup.
Typescript migration of original files.

2022-09-16 03:40 UTC, AJGR89 reviewed
initial setup complete

2022-09-18 06:03 UTC, rodrigotonso requested changes

2022-09-18 06:03 UTC, rodrigotonso commented on .eslintrc.json
> +        "no-console": "off",
Un warning estaría bueno

2022-09-18 06:03 UTC, rodrigotonso commented on .gitignore
> +.idea
Es costumbre agregarle algunos archivos más
Buscar en internet un generador de gitignores y van a ver opciones interesantes para agregar como el .vscode

2022-09-18 06:03 UTC, rodrigotonso commented on package.json
> +    "dev": "ts-node src/bin/www.ts"
¿Por que el archivo principal es www.ts dentro de bin?
Que folder estructure se eligió al final???

2022-09-18 06:03 UTC, rodrigotonso commented on src/app.ts
> +app.use((err: any, req: Request, res: Response, next: NextFunction) => {
Se puede usar en lugar del tipo any el tipo unknow???
O tipar a todos los params como ErrorRequestHandler???

2022-09-18 06:03 UTC, rodrigotonso commented on src/config/config.ts
> +    username: process.env.DB_USER,
Se suele agregar un valor || por lo menos un localhost

2022-09-18 06:03 UTC, rodrigotonso commented on src/migrations/20200921070147-create-role.ts
> +  up: async (queryInterface: any, Sequelize: any) => {
Sequery no ofreció tipos distintos a any ¿?¿?¿?

2022-09-18 06:03 UTC, rodrigotonso commented on src/migrations/20200921070147-create-role.ts
> +  down: async (queryInterface: any, Sequelize: any) => {
¿Any?

2022-09-18 06:03 UTC, rodrigotonso commented on src/models/role.ts
> +    static associate(models: any) {
any?

2022-09-18 06:03 UTC, rodrigotonso commented on tsconfig.json
> +{
Algunos recomiendan dejar el tsconfig con todas las lineas comentadas, yo soy más de los que me gusta solo dejar lo explicito, sino cuesta mucho saber que esta haciendo ese archivo.
¿Borramos todos los comentarios??

2022-09-18 16:36 UTC, NovoaMartin commented on package.json
> +    "dev": "ts-node src/bin/www.ts"
Por ahora se mantuvo la folder structure que vino con el proyecto, app.js exporta un Application de express y www crea el httpServer.

2022-09-18 16:40 UTC, NovoaMartin commented on src/app.ts
> +app.use((err: any, req: Request, res: Response, next: NextFunction) => {
ErrorRequestHandler usa any para el parametro err.

2022-09-19 16:14 UTC, rodrigotonso commented on package.json
> +    "dev": "ts-node src/bin/www.ts"
Perfecto, me olvidó la folder structure que viene (no es mi favorita jajaj)

2022-09-19 16:16 UTC, rodrigotonso commented on src/app.ts
> +app.use((err: any, req: Request, res: Response, next: NextFunction) => {
Sisi, pero es para no tener distribuidos any por todo el código ademas que deja un poco más prolija la linea
(Ver any sueltos siempre me llama la atención) por eso va más como pregunta que como pedido

2022-09-19 16:17 UTC, rodrigotonso approved these changes

2022-09-19 19:43 UTC, merged