Feature/ot292 33
alkemyTech/OT292-server pull request #10
Opened 2022-09-20 03:41 UTC by AJGR89

ADD jwt handler
**TICKET:** https://alkemy-labs.atlassian.net/browse/OT292-33
![imagen](https://user-images.githubusercontent.com/57067632/191162349-86bfec7b-551c-4d93-b12b-43c7329ee4ec.png)

2022-09-20 23:20 UTC, NovoaMartin requested changes

2022-09-20 23:20 UTC, NovoaMartin commented on src/app.ts
> -
¿No es el otro import el que hay que mantener?

2022-09-20 23:20 UTC, NovoaMartin commented on src/app.ts
> +app.use('/users',usersRouter);
Espacio

2022-09-20 23:20 UTC, NovoaMartin commented on src/routes/index.ts
> +  res.send({token});
Codigo innecesario

2022-09-20 23:20 UTC, NovoaMartin commented on src/types/index.d.ts
> +      userId?: string;
userId es un "number?"

2022-09-20 23:55 UTC, AJGR89 commented on src/routes/index.ts
> +  res.send({token});
resuelto

2022-09-20 23:58 UTC, AJGR89 commented on src/app.ts
> -
No entiendo de cual de los dos me estas hablando

2022-09-21 00:07 UTC, AJGR89 commented on src/types/index.d.ts
> +      userId?: string;
no lo vi necesario, la función **generateToken** recibe un string, entiendo que el endpoint de autenticación de usuario hara uso de esta función para generar el token, y que allí se puede hacer la conversion de number a string. Todo esto teniendo en cuentas que la el metodo sign de jsonwebtoken recibe un payload de tipo string.

2022-09-21 00:32 UTC, NovoaMartin commented on src/types/index.d.ts
> +      userId?: string;
Al ser userId un number en el modelo y la base de datos creo que conviene mas usar el mismo tipo en todo el proyecto.

El metodo sign puede recibir un objeto de esta forma:
jwt.sign({
userId: user.id;
});

2022-09-22 00:13 UTC, FedericoStagnaro commented on src/middlewares/auth.ts
> +    const payload = verifyToken(token) as { id: string };
seria mas adecuado ponerle el tipo id number?
```suggestion
    const payload = verifyToken(token) as { id: number };
```

2022-09-22 02:49 UTC, AJGR89 commented on src/types/index.d.ts
> +      userId?: string;
realizado

2022-09-22 02:50 UTC, AJGR89 commented on src/middlewares/auth.ts
> +    const payload = verifyToken(token) as { id: string };
realizado

2022-09-22 05:36 UTC, rodrigotonso approved these changes

2022-09-22 05:36 UTC, rodrigotonso commented on src/middlewares/auth.ts
> +    if (token.startsWith('Bearer ')) {
Esta repetido con el PR
https://github.com/alkemyTech/OT292-server/pull/9

Mismo comentarios que alla
Al hacer un ticket nuevo hay que volver a develop, hacer pull de todo y desde ahi crear una rama nueva

2022-09-22 05:36 UTC, merged