feature/OT292 32
alkemyTech/OT292-server pull request #23
Opened 2022-09-22 16:48 UTC by fredyvaron

TICKET: [https://alkemy-labs.atlassian.net/browse/OT292-32](url)
Envío de email de Bienvenida con la herramienta sendgrid con el template del ticket 31

2022-09-22 20:12 UTC, NovoaMartin requested changes
sendmail deberia ser parte de mailService(no es un controlador)

2022-09-22 20:12 UTC, NovoaMartin commented on src/controllers/sendmail.ts
> +  console.log("ingreso a sendwelcome email");
Sacar los console.log

2022-09-22 20:12 UTC, NovoaMartin commented on src/controllers/sendmail.ts
> +  console.log(organizations.image);
console.log

2022-09-22 20:12 UTC, NovoaMartin commented on src/services/mailService.ts
> +          console.log(data)
console.log

2022-09-24 22:36 UTC, rodrigotonso approved these changes

2022-09-24 22:36 UTC, rodrigotonso commented on src/controllers/sendmail.ts
> +  const organizations: any = await   db.Organization.findOne({
no se pudo crear un interfaz para el any ¿?

2022-09-24 22:36 UTC, rodrigotonso commented on src/controllers/sendmail.ts
> +  const organizations: any = await   db.Organization.findOne({
Hay un motivante importante para el exclude ¿?

2022-09-24 22:37 UTC, merged