Featured/ot292 36
alkemyTech/OT292-server pull request #37
Opened 2022-09-26 21:00 UTC by perex125

### Summary

- controller updateUser added
- router update user added
- validation user added

### Evidance
No admin:
![no admin](https://user-images.githubusercontent.com/50639892/192379336-5c3c72f7-a5d8-4b47-93a7-a8fa40a5cca5.png)
![no admin 2](https://user-images.githubusercontent.com/50639892/192379354-4ba7ab65-d09e-47a9-9183-51a7d36a7322.png)
![no admin 3](https://user-images.githubusercontent.com/50639892/192379380-1eee2f85-25c3-405c-ab94-4482826d1b3d.png)

Admin
![admin](https://user-images.githubusercontent.com/50639892/192379444-983fe38d-d723-459b-8317-46c044e838fa.png)
![admin2](https://user-images.githubusercontent.com/50639892/192379467-fa280fc4-c627-413d-995c-6bd9478f4a41.png)

2022-09-26 21:19 UTC, NovoaMartin requested changes

2022-09-26 21:19 UTC, NovoaMartin commented on src/models/role.ts
> +  declare updated_at: CreationOptional<Date>;
Las variables van en camelCase

2022-09-26 21:19 UTC, NovoaMartin commented on src/models/role.ts
> +    updated_at: DataTypes.DATE,
Camelcase

2022-09-26 21:19 UTC, NovoaMartin commented on src/models/role.ts
> +    modelName: 'role',
Los nombres de los modelos estan dados por el nombre del a clase(mayuscula)

2022-09-26 21:24 UTC, NovoaMartin commented on src/middleware/verifyOwnership.ts
> +  if (Number(id) === Number(userId)) {
req.userId ya es un number

2022-09-26 21:49 UTC, perex125 commented on src/middleware/verifyOwnership.ts
> +  if (Number(id) === Number(userId)) {
Si

2022-09-26 21:49 UTC, perex125 commented on src/models/role.ts
> +    modelName: 'role',
Mala mia, me devolvia mal el endpoint

2022-09-26 21:49 UTC, perex125 commented on src/models/role.ts
> +    updated_at: DataTypes.DATE,
Mala mia, me devolvia mal el endpoint

2022-09-26 21:49 UTC, perex125 commented on src/models/role.ts
> +  declare updated_at: CreationOptional<Date>;
Mala mia, me devolvia mal el endpoint

2022-09-29 20:05 UTC, rodrigotonso approved these changes

2022-09-29 20:05 UTC, rodrigotonso commented on src/controllers/users.ts
> +import db from '../models/index';
no hace falta aclarar los index en las imports

2022-09-29 20:07 UTC, merged