adding Model of comment, migration of comment, routes of comment, con…
alkemyTech/OT292-server pull request #78
Opened 2022-10-08 23:16 UTC by Juan-Vera-ok

…troller of comment and fixing README

2022-10-09 00:09 UTC, NovoaMartin requested changes

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +    declare new_id:ForeignKey<News>;
camelCase aca

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +    declare content: string;
Tiene que llamarse body

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +    declare type: string;
type esta de mas

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +        type: DataTypes.INTEGER.UNSIGNED,
Esta como unsigned aca y como signed en la migracion

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +        allowNull: true,
¿Tiene sentido un comentario sin autor?

camelCase

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +        type: DataTypes.INTEGER,
Unsigned
camelCase

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +        allowNull: true,
¿Tiene sentido un comentario sin una new?

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +      content: {
body

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +      },
Type esta de mas

2022-10-09 00:09 UTC, NovoaMartin commented on src/models/comment.ts
> +        allowNull:true,
No pueden ser null

2022-10-11 03:12 UTC, NovoaMartin submitted a review, later dismissed
Trata de subir los cambios con un push normal(no un force push)

2022-10-11 03:12 UTC, NovoaMartin commented on src/controllers/comments.ts
> +}
Pasar eslint.

Este endpoint no era parte del ticket.

2022-10-11 03:12 UTC, NovoaMartin commented on src/controllers/comments.ts
> +  };
Este endpoint no era parte del ticket.

Camelcase en los req.body.
Cambiar CommentClass por db.Comment

2022-10-11 03:12 UTC, NovoaMartin commented on src/migrations/20220916191925-create-user.ts
> +        type: Sequelize.INTEGER.UNSIGNED
Esto estaba como signed. El cambio rompe el resto del codigo.

2022-10-11 03:12 UTC, NovoaMartin commented on src/models/user.ts
> +      type: DataTypes.INTEGER.UNSIGNED,
Mantener el type anterior

2022-10-11 03:12 UTC, NovoaMartin commented on src/routes/comments.ts
> +router.get('/:comment_id',commentsController.getCommentById)
No es parte del ticket

2022-10-13 21:12 UTC, rodrigotonso approved these changes

2022-10-13 21:12 UTC, merged