Endpoint comments
alkemyTech/OT292-server pull request #89
Opened 2022-10-16 21:50 UTC by Juan-Vera-ok

2022-10-17 16:20 UTC, NovoaMartin requested changes, later dismissed

2022-10-17 16:20 UTC, NovoaMartin commented on src/controllers/comments.ts
> +        return res.status(400).json(error);
return next(createHttpError(500, error.message));

2022-10-17 16:20 UTC, NovoaMartin commented on src/controllers/comments.ts
> +        return res.status(201).json(commentSaved);
La respuesta deberia ser:
{
status: 201
message: commentSaved
}

2022-10-17 16:20 UTC, NovoaMartin commented on src/migrations/20221008173717-create-comment.ts
> +        type: DataTypes.INTEGER,
Mantener como unsigned

2022-10-17 16:20 UTC, NovoaMartin commented on src/routes/comments.ts
> +router.post('/',commentsController.createComment)
Falta validacion

2022-10-20 21:27 UTC, NovoaMartin requested changes

2022-10-20 21:27 UTC, NovoaMartin commented on src/controllers/comments.ts
> +        });
El usuario deberia estar autenticado, esta validacion es innecesaria.

2022-10-20 21:27 UTC, NovoaMartin commented on src/validations/commentValidator.ts
> +]
Falta el middleware para los errores, revisa como estan hechos los otros.

2022-10-20 23:34 UTC, merged

2022-10-21 00:41 UTC, Juan-Vera-ok commented on src/controllers/comments.ts
> +        });
Si no hago esa validación no me compila