init coding middleware for authenticated users
alkemyTech/OT292-server pull request #9
Opened 2022-09-20 03:36 UTC by AJGR89

Authenticated user Middleware 
https://alkemy-labs.atlassian.net/browse/OT292-27

![imagen](https://user-images.githubusercontent.com/57067632/191161909-399868fe-f079-458e-b08f-ac102a304dac.png)

2022-09-21 14:31 UTC, rodrigotonso requested changes

2022-09-21 14:31 UTC, rodrigotonso commented on src/middlewares/auth.ts
> +    if (token.startsWith('Bearer ')) {
si no empieza con Bearer que pasa?

2022-09-21 14:31 UTC, rodrigotonso commented on src/middlewares/auth.ts
> +    req.userId = payload.id;
¿Por que hacemos esto?

2022-09-21 14:46 UTC, AJGR89 commented on src/middlewares/auth.ts
> +    if (token.startsWith('Bearer ')) {
No sería valido, retorna error token invalid

2022-09-21 15:00 UTC, AJGR89 commented on src/middlewares/auth.ts
> +    req.userId = payload.id;
8-> retiro el string "Bearer " del token
10-  convierto la respuesta de jw.verify ene lt ipo objeto {id: string}
11-> coloco el id obtenido en el request de la solicitud

2022-09-22 05:34 UTC, rodrigotonso approved these changes

2022-09-22 05:34 UTC, merged